<?php
echo '<!doctype html>';
echo '<html lang="en" class="no-js">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '<link rel="stylesheet" href="css/reset.css">';
echo '<link rel="stylesheet" href="css/style.css">';
echo '<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />';
echo '<script src="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"></script>';
echo '<link rel="stylesheet" href="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.css" />';
echo '<link rel="stylesheet" href="css/style_map.css">';
echo '<script src="js/modernizr.js"></script>';
echo '<title>ParkoFriend | Your friend to solve all parking problems.</title>';
echo '<style>';
echo 'body {font-family: Arial, sans-serif; margin: 0; padding: 0;}';
echo '.container {position: relative; height: 100vh;}';
echo '.dropdown {position: absolute; top: 30px; right: 30px; background-color: #f9f9f9; border: 1px solid #ddd; border-radius: 5px; padding: 10px; display: none;}';
echo '.dropdown ul {list-style-type: none; padding: 0;}';
echo '.dropdown ul li {padding: 5px 10px; cursor: pointer;}';
echo '.dropdown ul li:hover {background-color: #ddd;}';
echo '.dropdown-toggle {position: absolute; top: 10px; right: 10px; width: 50px; height: 50px; background-color: #007bff; color: #fff; border-radius: 50%; text-align: center; line-height: 50px; cursor: pointer;}';
echo '</style>';
echo '</head>';
echo '<body>';
echo '<header>';
echo '<div class="cd-dropdown-wrapper">';
echo '<a class="cd-dropdown-trigger" href="#0">Menu</a>';
echo '<nav class="cd-dropdown">';
echo '<h2>Title</h2>';
echo '<a href="#0" class="cd-close">Close</a>';
echo '<ul class="cd-dropdown-content">';
echo '<li><form class="cd-search"><input type="search" placeholder="Search..."></form></li>';
echo '<li><a href="http://codyhouse.co/?p=748">About Us</a></li>';
echo '<li><a href="http://codyhouse.co/?p=748">Contact</a></li>';
echo '<li><a href="http://codyhouse.co/?p=748">Privacy Policies</a></li>';
echo '<li><a href="http://codyhouse.co/?p=748">Logout</a></li>';
echo '</ul>';
echo '</nav>';
echo '</div>';
echo '</header>';
echo '<main class="cd-main-content">';
echo '<section class="map_area" id="map_content"><div id="map"></div></section>';
echo '<section class="destination_acquire"><div class="destination1"></div></section>';
echo '</main>';
echo '<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>';
echo '<script src="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.js"></script>';
echo '<script src="js/jquery-2.1.1.js"></script>';
echo '<script src="js/jquery.menu-aim.js"></script>';
echo '<script src="js/main.js"></script>';
echo '<script src="js/script_for_map.js"></script>';
echo '<div class="container">';
echo '<div class="dropdown" id="myDropdown">';
echo '<ul>';
echo '<li>User name</li>';
echo '<li>Credits</li>';
echo '<li>Active bookings</li>';
echo '<li>Past bookings</li>';
echo '</ul>';
echo '</div>';
echo '<div class="dropdown-toggle" onclick="toggleDropdown()">☰</div>';
echo '</div>';
echo '<script>';
echo 'function toggleDropdown() {';
echo 'var dropdown = document.getElementById("myDropdown");';
echo 'if (dropdown.style.display === "block") {';
echo 'dropdown.style.display = "none";';
echo '} else {';
echo 'dropdown.style.display = "block";';
echo '}';
echo '}';
echo '</script>';
echo '</body>';
echo '</html>';
?>
